export const NAMESPACE = 'WEB3_REDUX';
export const WEB3_API = {
  'net.getListening': {},
  'net.getPeerCount': {},
  'version.getNode': {},
  'version.getNetwork': {},
  'version.getEthereum': {},
  'version.getWhisper': {},
  'eth.getBalance': {},
  'eth.getCode': {},
  'eth.getTransactionCount': {},
  'eth.getStorageAt': {},
  'eth.getSyncing': {},
  'eth.getCoinbase': {},
  'eth.getMining': {},
  'eth.getHashrate': {},
  'eth.getGasPrice': {},
  'eth.getAccounts': {},
  'eth.getBlockNumber': {},
  'eth.getBlock': {},
  'eth.getBlockTransactionCount': {},
  'eth.getUncle': {},
  'eth.getTransaction': {},
  'eth.getTransactionFromBlock': {},
  'eth.getTransactionReceipt': {},
};
