import { createTransaction, getTransaction } from './actions';
export default {
  'net.getListening': {},
  'net.getPeerCount': {},
  'version.getNode': {},
  'version.getNetwork': {},
  'version.getEthereum': {},
  'version.getWhisper': {},
  'eth.getBalance': {},
  'eth.getCode': {},
  'eth.getTransactionCount': {},
  'eth.getStorageAt': {},
  'eth.getSyncing': {},
  'eth.getCoinbase': {},
  'eth.getMining': {},
  'eth.getHashrate': {},
  'eth.getGasPrice': {},
  'eth.getAccounts': {},
  'eth.getBlockNumber': {},
  'eth.getBlock': {},
  'eth.getBlockTransactionCount': {},
  'eth.getUncle': {},
  'eth.getTransactionFromBlock': {},
  'eth.getTransaction': {
    collection: 'transactions',
    actionCreator: getTransaction,
  },
  'eth.getTransactionReceipt': {
    collection: 'transactions',
    actionCreator: getTransaction,
  },
  'eth.sendTransaction': {
    collection: 'transactions',
    actionCreator: createTransaction,
  },
  'eth.sendRawTransaction': {
    collection: 'transactions',
    actionCreator: createTransaction,
  },
};
