import * as transactionActions from './actions/transactions';
export default {
  'net.getListening': {},
  'net.getPeerCount': {},
  'version.getNode': {},
  'version.getNetwork': {},
  'version.getEthereum': {},
  'version.getWhisper': {},
  'eth.getBalance': {},
  'eth.getCode': {},
  'eth.getTransactionCount': {},
  'eth.getStorageAt': {},
  'eth.getSyncing': {},
  'eth.getCoinbase': {},
  'eth.getMining': {},
  'eth.getHashrate': {},
  'eth.getGasPrice': {},
  'eth.getAccounts': {},
  'eth.getBlockNumber': {},
  'eth.getBlock': {},
  'eth.getBlockTransactionCount': {},
  'eth.getUncle': {},
  'eth.getTransaction': { actions: transactionActions.actions },
  'eth.getTransactionFromBlock': {},
  'eth.getTransactionReceipt': { actions: transactionActions.actions },
};
